//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <ARRAY_LENGTH>
 */
public class ArrayLengthExpression implements Node {
   public NodeToken f0;

   public ArrayLengthExpression(NodeToken n0) {
      f0 = n0;
   }

   public ArrayLengthExpression() {
      f0 = new NodeToken("length");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

